name: Linting

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Haskell Linter
      uses: domdere/haskell-lint-action@v1.0.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
