name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Stack
      uses: mstksg/setup-stack@v2
      
    - name: stack install, build and test
      run: |
        stack install
        stack build
        stack test
