name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v1
    
    - name: Setup Stack
      uses: mstksg/setup-stack@v2
    
    - name: Cache Stack downloads
      uses: actions/cache@v1
      env:
        cache-name: cache-stack-modules
      with:
        path: /home/runner/.stack/
        key: ${{ hashFiles('**/stack.yaml.lock') }}
      
    - name: stack install, build and test
      run: |
        stack build
        stack test
        
    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ${{ stack path --local-install-root }}/bin
